baseURL = 'https://ahmedmujtabanizamani.github.io/myweb/'
languageCode = 'en-US'

title = 'Hugo and Stork'

disableKinds = ['RSS','sitemap','taxonomy','term']
enableGitInfo = true

[outputFormats.stork]
mediaType = 'application/json'
baseName = 'stork.config'
isPlainText = true

[outputs]
home = ['html','stork']
